spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  sql:
    init:
      mode: never
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: '${MYSQL_Password}'
    username: 'root'
    url: jdbc:mysql://localhost:3306/car_Rental?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC

LuxuryCarRentals:
  remember.me.key: ${REMEMBER_ME_KEY:12345}

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor: TRACE
#        SQL: DEBUG
#      nodeValue: WARN
#    blog: WARN
#server:
#  port: 8080